basePath: /v2
definitions:
  entities.Access:
    properties:
      code:
        type: string
    type: object
  entities.Note:
    properties:
      note:
        type: integer
      number:
        type: integer
      surveyCode:
        type: string
    type: object
  entities.Survey:
    properties:
      code:
        type: string
      endDate:
        type: string
      notes:
        items:
          $ref: '#/definitions/entities.Note'
        type: array
      startDate:
        type: string
      teamName:
        type: string
    type: object
  entities.Team:
    properties:
      frequency:
        type: integer
      name:
        type: string
      num_mumbers:
        type: integer
      startDate:
        type: string
      surveys:
        items:
          $ref: '#/definitions/entities.Survey'
        type: array
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /access:
    post:
      consumes:
      - application/json
      description: you should send a survey code to access
      parameters:
      - description: string
        in: body
        name: Code
        required: true
        schema:
          $ref: '#/definitions/entities.Access'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Access to survey
      tags:
      - Autentication
  /survey/:surveyCode:
    delete:
      consumes:
      - application/json
      description: returns a empty survey
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Delete a survey
      tags:
      - Survies
    get:
      consumes:
      - application/json
      description: returns survey by it code
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Get survey by it code
      tags:
      - Survies
    put:
      consumes:
      - application/json
      description: returns the survey updated
      parameters:
      - description: Date
        in: body
        name: StartDate
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: Date
        in: body
        name: EndDate
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: String
        in: body
        name: Code
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: String
        in: body
        name: TeamName
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Update a survey
      tags:
      - Survies
  /survey/:surveyCode/addNotes:
    post:
      consumes:
      - application/json
      description: you should send an array of Notes. Those will be saved in the survey with code provided.
      parameters:
      - description: int
        in: body
        name: Number
        required: true
        schema:
          $ref: '#/definitions/entities.Note'
      - description: int
        in: body
        name: Note
        required: true
        schema:
          $ref: '#/definitions/entities.Note'
      - description: string
        in: body
        name: surveyCode
        required: true
        schema:
          $ref: '#/definitions/entities.Note'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Add notes to survey
      tags:
      - Survies
  /survey/create:
    post:
      consumes:
      - application/json
      description: returns the survey created
      parameters:
      - description: Date
        in: body
        name: StartDate
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: Date
        in: body
        name: EndDate
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: String
        in: body
        name: Code
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      - description: String
        in: body
        name: TeamName
        required: true
        schema:
          $ref: '#/definitions/entities.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Create a new survey
      tags:
      - Survies
  /survey/result/:surveyCode:
    get:
      consumes:
      - application/json
      description: returns the average of all the survey notes
      produces:
      - application/json
      responses:
        "200":
          description: int
      summary: Survey result
      tags:
      - Survies
  /survies:
    get:
      consumes:
      - application/json
      description: returns all survies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Survey'
      summary: Get all survies
      tags:
      - Survies
  /team/:teamName:
    delete:
      consumes:
      - application/json
      description: returns a team updated
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Team'
      summary: Update a team
      tags:
      - Teams
    get:
      consumes:
      - application/json
      description: returns one team by teamName
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Team'
      summary: Get one team
      tags:
      - Teams
    put:
      consumes:
      - application/json
      description: returns a team updated
      parameters:
      - description: String
        in: body
        name: Name
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Num_members
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Frequency
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: Date
        in: body
        name: StartDate
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Team'
      summary: Update a team
      tags:
      - Teams
  /team/create:
    post:
      consumes:
      - application/json
      description: returns a team created
      parameters:
      - description: String
        in: body
        name: Name
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Num_members
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Frequency
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: Date
        in: body
        name: StartDate
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Team'
      summary: Create a new team
      tags:
      - Teams
  /teams:
    get:
      consumes:
      - application/json
      description: returns all teams
      parameters:
      - description: String
        in: body
        name: Name
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Num_members
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: int
        in: body
        name: Frequency
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      - description: Date
        in: body
        name: StartDate
        required: true
        schema:
          $ref: '#/definitions/entities.Team'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Team'
      summary: Get all teams
      tags:
      - Teams
swagger: "2.0"
